# docker-compose up --build
version: "3.9"
services:
  consul:
    image: hashicorp/consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600/udp

  rabbit-mq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "6831:6831"
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: true

  order-mongo:
    image: "mongo:7.0.14"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  mongo-express:
    image: "mongo-express:1.0.2-20-alpine3.19" #MongoDB 可视化管理工具
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@order-mongo:27017/
      ME_CONFIG_BASICAUTH: false