apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: gorder
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 6831
              protocol: UDP  # Jaeger Agent 默认使用 UDP
            - containerPort: 16686  # Jaeger UI
            - containerPort: 14268  # Jaeger HTTP Collector
            - containerPort: 4318   # OTLP HTTP
            - containerPort: 4317   # OTLP gRPC
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: gorder
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: agent-udp
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: ui
      port: 16686
      targetPort: 16686
      nodePort: 31686
    - name: collector-http
      port: 14268
      targetPort: 14268
      nodePort: 31268
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317