# Redis 配置 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: gorder
data:
  redis.conf: |
    port 6379
    save 900 1
    save 300 10
    dir /data
    dbfilename dump.rdb
    protected-mode no

---
# Redis 无头 Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: gorder
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis

---
# Redis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: gorder
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:7.0-alpine
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 10Gi

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: redis-external-service
  namespace: gorder
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31079  # 节点端口 (30000-32767)
  selector:
    app: redis

