apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: gorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.2-20-alpine3.19
          imagePullPolicy: IfNotPresent
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-root-creds
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-creds
                  key: password
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://$(ME_CONFIG_MONGODB_ADMINUSERNAME):$(ME_CONFIG_MONGODB_ADMINPASSWORD)@order-mongo-0.order-mongo-headless:27017/?authSource=admin"
          ports:
            - containerPort: 8081
              name: express

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: gorder
spec:
  type: NodePort  # 外部通过节点 IP:NodePort 访问（生产环境建议用 LoadBalancer 或 Ingress）
  ports:
    - port: 8082  # Service 端口
      targetPort: 8081  # 容器端口
      nodePort: 31081  # 节点端口
  selector:
    app: mongo-express  # 匹配 mongo-express Pod 的标签