#secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-root-creds
  namespace: gorder
type: Opaque
data:
  username: cm9vdA==  # root
  password: cGFzc3dvcmQ= #password

---
#headless-service
apiVersion: v1
kind: Service
metadata:
  name: order-mongo-headless
  namespace: gorder
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  selector:
    app: order-mongo

---
#statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-mongo
  namespace: gorder
spec:
  serviceName: order-mongo-headless
  replicas: 1
  selector:
    matchLabels:
      app: order-mongo
  template:
    metadata:
      labels:
        app: order-mongo
    spec:
      containers:
        - name: order-mongo
          image: mongo:7.0.14
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-root-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-creds
                  key: password
            - name: MONGO_INITDB_BIND_IP
              value: "0.0.0.0"
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path" #需本地有该storageClass
        resources:
          requests:
            storage: 10Gi

---
# 新增外部访问 Service（NodePort 类型）
apiVersion: v1
kind: Service
metadata:
  name: order-mongo-external
  namespace: gorder
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31017
      name: mongo
  selector:
    app: order-mongo