fallback-grpc-addr: 127.0.0.1:3030
order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

consul:
#  addr: 127.0.0.1:8500
  addr: 39.98.76.224:30085
#  addr: 192.168.3.221:30085

rabbitmq:
  user: guest
  password: guest
#  host: 127.0.0.1
  host: 39.98.76.224
#  host: 192.168.3.221
#  port: 5672
  port: 30672
  max-retry: 3

stripe-key: "${STRIPE_KEY}" # 去环境变量里找
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}" # 去环境变量里找