fallback-grpc-addr: 127.0.0.1:3030
dial-grpc-timeout: 10

jaeger:
  url: "http://39.98.76.224:31268/api/traces" # 31268是14268的nodePort端口

order:
  service-name: order
  server-to-run: http
  http-addr: 0.0.0.0:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 0.0.0.0:8284
  grpc-addr: 127.0.0.1:5004

kitchen:
  service-name: kitchen

consul:
#  addr: 127.0.0.1:8500
  addr: 39.98.76.224:30085
#  addr: 192.168.3.221:30085

rabbitmq:
  user: guest
  password: guest
#  host: 127.0.0.1
  host: 39.98.76.224
#  host: 192.168.3.221
#  port: 5672
  port: 30672
  max-retry: 3

mongo:
  user: root
  password: password
  host: 39.98.76.224
#  port: 27017
  port: 31017
  db-name: "order"
  coll-name: "order"

stripe-key: "${STRIPE_KEY}" # 去环境变量里找
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}" # 去环境变量里找