fallback-grpc-addr: 127.0.0.1:3030
order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

consul:
  addr: 127.0.0.1:8500

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

stripe-key: "${STRIPE_KEY}" # 去环境变量里找